### ISSUE TITLE
DataBase management

### ISSUE THREAD

**Issue by nishantkr18** [nishantkr18/IIT-BHU-app#106]
@mohit-mangal I think there is a problem with database management for council's is_por_holder.. with my id, I receive `true` for SnTC's `is_por_holder`, when I call the backnd API, but false in the app.. Thats why I a POR holder cannot change description for Council. Kindly have a look.

**Comment by mohit-mangal** [comment]
Actually it isn't related to database, until now council API wasn't requested with token. I have fixed it
