### ISSUE TITLE
Problem in Description TextFormFeild

### ISSUE THREAD

**Issue by nishantkr18** [nishantkr18/IIT-BHU-app#119]
While editing description, its not possible to scroll the textformfeild with keyboard open. So it becomes difficult to edit description for the workshop. 
cc/ @aksayushx

**Comment by aksayushx** [comment]
As of now, it will be scrollable only when the size of the existing description exceeds the container size. I will try to fix this soon.

**Comment by nishantkr18** [comment]
Cool.
