### ISSUE TITLE
Refresh after editing

### ISSUE THREAD

**Issue by nishantkr18** [nishantkr18/IIT-BHU-app#128]
After editing club and council description, one needs to 'refresh in settings' to view changes.. this needs to be rectified for atleast the one who is editing..

A solution would be to add pull-to-refresh for clubs and councils, so that the database gets updated with new data when the user wants..

/cc @mohit-mangal

**Comment by mohit-mangal** [comment]
On refreshing a club/council, should only that club/council get refreshed or should all the clubs and councils get refreshed.
@nishantkr18

**Comment by nishantkr18** [comment]
Only that club/council should make more sense, as it will require least amount of api calls.
