### ISSUE TITLE
Problem in opening club page for some clubs

### ISSUE THREAD

**Issue by nishantkr18** [nishantkr18/IIT-BHU-app#73]
![image](https://user-images.githubusercontent.com/44468894/80858325-54812200-8c76-11ea-9986-bee7b82ec519.png)
This is the error I get when entering some clubs. I think its related to the use of storage of clubs and council data. @mohit-mangal , please have a look.. There seems to be a lot of errors in database.

**Comment by mohit-mangal** [comment]
successfully addressed :)
